PREFIX core: <https://ontology.unifiedcyberontology.org/uco/core/>
PREFIX observable: <https://ontology.unifiedcyberontology.org/uco/observable/>
PREFIX ioi-ext: <https://ioi-framework.github.io/ns/ioi-ext/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT DISTINCT
  ?officeFile ?fileName ?filePath ?xmlCreated ?mftSiCreated ?mftFnCreated
WHERE {
  GRAPH <https://ioi-framework.github.io/cases/AF-012/graphs/office> {
    ?officeFile a observable:File ;
                core:hasFacet ?xmlFacet , ?mftFacet , ?fileFacet .

    ?xmlFacet a ioi-ext:OfficeXmlMetadataFacet ;
              ioi-ext:dctermsCreated ?xmlCreated .

    ?mftFacet a observable:MftRecordFacet ;
              observable:mftFileNameCreatedTime ?mftFnCreated .

    ?fileFacet a observable:FileFacet ;
               observable:fileName ?fileName ;
               observable:filePath ?filePath ;
               observable:observableCreatedTime ?mftSiCreated .

    FILTER(xsd:dateTime(?xmlCreated) < xsd:dateTime(?mftSiCreated))
  }
}
ORDER BY ?filePath
