PREFIX core: <https://ontology.unifiedcyberontology.org/uco/core/>
PREFIX observable: <https://ontology.unifiedcyberontology.org/uco/observable/>
PREFIX ioi-ext: <https://ioi-framework.github.io/ns/ioi-ext/>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?event_type ?time ?file_name ?update_reasons ?seed_uri ?seed_graph
WHERE {
  {
    GRAPH <https://ioi-framework.github.io/cases/AF-007/graphs/security> {
      ?event a observable:EventRecord ;
             core:hasFacet ?std_facet, ?custom_facet .
      ?std_facet a observable:EventRecordFacet ;
                 observable:eventID "1102" ;
                 observable:startTime ?time ;
                 observable:eventRecordText ?text .
      ?custom_facet a ioi-ext:EventLogFacet ;
                    ioi-ext:channel "Security" .
      BIND("Event 1102 - Log Cleared" AS ?event_type)
      BIND(?text AS ?file_name)
      BIND("" AS ?update_reasons)
      BIND(?event AS ?seed_uri)
      BIND("evtx" AS ?seed_graph)
    }
  }
  UNION
  {
    GRAPH <https://ioi-framework.github.io/cases/AF-007/graphs/usn> {
      ?file a observable:File ;
            core:hasFacet ?fileFacet, ?usnFacet .
      ?fileFacet a observable:FileFacet ;
                 observable:fileName ?filename .
      ?usnFacet a ioi-ext:UsnFacet ;
                ioi-ext:updateReasons ?reasons ;
                ioi-ext:updateTimestamp ?time .
      FILTER(CONTAINS(?filename, "Security"))
      FILTER(CONTAINS(?reasons, "DataTruncation"))
      BIND("USN DataTruncation" AS ?event_type)
      BIND(?filename AS ?file_name)
      BIND(?reasons AS ?update_reasons)
      BIND(?file AS ?seed_uri)
      BIND("usn" AS ?seed_graph)
    }
  }
}
ORDER BY ?time
